config/routes.rb
Rails.application.routes.draw do

  # static
  root 'static_pages#arazin'
  
  get '/magicdeal',to:'static_pages#magicdeal'
  get '/ranking',to:'static_pages#ranking'
  get '/help',to:'static_pages#help'
  get '/ec',to:'static_pages#ec'  # 出店(暫定)
  
  get '/histories',to:'static_pages#histories'
  get '/clips',to:'static_pages#clips'
  get '/boughts',to:'static_pages#boughts'
  
  
  # users
  get '/signup',to: 'users#new'
  post '/signup',  to: 'users#create'
  
  # sessions
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :relationships,       only: [:create, :destroy]
  
  resources :items do
    member do
      post "add_clip", to: "clips#create"
    end
  end
  
  resources :clips, only: [:destroy]
  
  # カート
  resources :carts, only: [:show]
  
  post '/add_item', to:'carts#add_item'
  post '/update_item', to: 'carts#update_item'
  delete '/delete_item', to: 'carts#delete_item'
  
  post '/cart_login', to:'carts#cart_login'
  get '/cart_login', to:'carts#cart_login'
  
  # get '/cart_login',to:'carts#cart_login'
  post '/cart_login_create', to:'carts#cart_login_create'
  
  get '/pay_view',to:'carts#pay_view'
  post '/pay_view', to:'carts#pay'
  
  # resources :cards
  get '/card_create',to: 'cards#new'
  post '/card_create',to: 'cards#create'

  get '/pay_confirmation',to:'carts#pay_confirmation'

  # 他のポートフォリオ
  get '/cafe',to:'static_pages#cafe'
  get '/gallery',to: 'static_pages#gallery'
  get '/lp1',to: 'static_pages#lp1'
  get '/black_jack',to: 'static_pages#black_jack'
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  # 事前にログイン済みユーザーかどうか確認
  before_action :logged_in_user,only: [:histories,:clips,:boughts]
  
  # ルート
  def arazin
    @items = Item.all
    @items_rank_kaden = Item.where(category: "家電").order(sales: "DESC")
    @items_rank_norimono = Item.where(category: "乗り物").order(sales: "DESC")
    @items_rank_food = Item.where(category: "食品").order(sales: "DESC")
    
    if logged_in?
      @user = current_user
    end
  end
  
  def magicdeal
    @items = Item.all
  end
  
  def ranking
    @items_rank_kaden = Item.where(category: "家電").order(sales: "DESC")
    @items_rank_norimono = Item.where(category: "乗り物").order(sales: "DESC")
    @items_rank_food = Item.where(category: "食品").order(sales: "DESC")
  end
  
  def card
  end
  
  def help
  end
  
  def ec
  end
  
  def histories
    @histories = current_user.histories.page (params[:page])
    # @items = @user.items.page (params[:page])
  end
  
  def clips
    @clips = current_user.clips.page (params[:page])
    # @items = @user.items.page (params[:page])
  end
  
  def boughts
    @boughts = current_user.boughts.page (params[:page])
  end
  
  
  
  # 他のポートフォリオ
  def cafe
  end
  
  def gallery
  end

  def lp1
  end
  
  def black_jack
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_arazin-carousel.html.erb
<!--カルーセル-->
<div class="arazin-carousel">
  <div id="carouselExampleControls" class="carousel slide" data-ride="carousel" data-interval="10000">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <%= image_tag 'spring_sale',class:"d-block w-100",alt: "First slide"%>
      </div>
      <div class="carousel-item">
        <%= image_tag 'half_price',class:"d-block w-100",alt: "Second slide"%>
      </div>
      <div class="carousel-item">
       <%= image_tag 'web_sale',class:"d-block w-100",alt: "Third slide"%>
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>

app/views/static_pages/_arazin-head.html.erb
    <meta charset="utf-8">
    <meta name="description" content="ECサイト">
    <meta name="Keywords" content="ECサイト,商品,出店">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

app/views/static_pages/_arazin-side-menu.html.erb
<!--サイドメニュー1(画像と配達日)-->
<div class="arazin-side-menu1">
  <%= image_tag 'point_bonus',class:"side_image1",alt: "side_image1"%>
  <%= image_tag 'web_special',class:"side_image2",alt: "side_image2"%>

    <p class="araraku">ジンの翌日配達「ジン楽」</p>
  
  <div class="haitatubi">
    <p class="saitan">最短</p>
    <!--明日の日付を出力-->
    <div id="view_today"></div>
    <!--明日の曜日を出力-->
    <div id="view_youbi"></div>
  </div>
  
  <script>
    document.getElementById("view_today").innerHTML = getToday(0);
    document.getElementById("view_youbi").innerHTML = getYoubi();
  </script>
  
</div>
<!--サイドメニュー1(画像と配達日)終わり-->

<!--サイドメニュー2(ジャンル)開始-->
<div class="arazin-side-menu2 ">
  <div class="genre-menu clearfix">
    <p class="genre">カテゴリー</p>
  </div>
  
  <div class="genre-contens">
    <p><%= link_to '家電',{:controller=>"items",:action=>"index",:q=>{:category_eq=>'家電'}}%></p>
    <p><%= link_to '乗り物',{:controller=>"items",:action=>"index",:q=>{:category_eq=>'乗り物'}}%></p>
    <p><%= link_to '食品',{:controller=>"items",:action=>"index",:q=>{:category_eq=>'食品'}}%></p>
  </div>
  
  <div class="genre-menu clearfix">
    <p class="genre">マジックDEAL</p>
  </div>
  
  <div class="genre-contens">
    <p><%= link_to '40%ポイントバック',{:controller=>"items",:action=>"index",:q=>{:spoint_eq=>'40'}}%></p>
    <p><%= link_to '30%ポイントバック',{:controller=>"items",:action=>"index",:q=>{:spoint_eq=>'30'}}%></p>
  </div>
</div>

app/views/static_pages/_arazin-top-menu.html.erb
<!--トップメニュー-->
    <div class="arazin-top-menu">
      <div class="row top-col">
        
        <!--トップタイトル-->
        <div class="col-lg-1 col-sm-2 mb-lg-3">
          <div class="arazin-title">
            <h1><%= link_to "Zin", root_path %></h1>
          </div>
        </div>
        
        <!--検索フォーム-->
        <div class="col-lg-6 col-sm-12 mb-lg-3">
          <%= render 'static_pages/arazin-serch' %>
        </div>
        
        <!--トップアイコン-->
        <div class="col-lg-5 col-sm-12 mb-3">
          <!--買い物かご-->
          <%= link_to(current_cart,class: 'arazin-cart') do %>
            <span class ="icon-cart">
             <i class="fas fa-shopping-cart"></i> <p>買い物かご</p>
            </span>
          <% end %>
        
          <!--閲覧履歴-->
          <%= link_to(histories_path,class: 'arazin-browsing-history') do %>
            <span class ="icon-browsing-history">
             <i class="fas fa-history"></i> <p>閲覧履歴</p>
            </span>
          <% end %>
          
          <!--お気に入り-->
          <%= link_to(clips_path,class: 'arazin-favorite') do %>
            <span class ="icon-favorite">
             <i class="far fa-star"></i> <p>お気に入り</p>
            </span>
          <% end %>
          
          <!--購入履歴-->
          <%= link_to(boughts_path,class: 'arazin-purchase-history') do %>
            <span class ="icon-purchase-history">
             <i class="far fa-file-alt"></i> <p>購入履歴</p>
            </span>
          <% end %>
          
          </div>
      </div>
    </div>

app/views/static_pages/arazin.html.erb
<% provide(:title, "Home") %>

    <!--ナビバー-->
    <%= render 'static_pages/arazin-navbar' %>
  
    <!--トップメニュー-->
    <%= render 'static_pages/arazin-top-menu'%>
    
    <!--トップサブメニュー-->
    <%= render 'static_pages/arazin-top-sub'%>
    
    <!--カルーセル-->
    <%= render 'static_pages/arazin-carousel'%>
    
    <div class="static_pages/arazin-main">
      
        <div class="row">
          <div class="col-lg-2 col-md-3 d-none d-sm-block">
            <aside class="side">
               <!--サイドメニュー-->
              <%= render 'static_pages/arazin-side-menu'%>
            </aside>
          </div>
          
          <div class="col-lg-10 col-md-9 col-sm-12">
            <main class="main">
              <div class="slick1">
                <%= image_tag 'final_sale',class:"slick1-image1",alt: "advertisement"%>
                <%= image_tag '70',class:"slick1-image1",alt: "advertisement"%>
                <%= image_tag 'clearlance',class:"slick1-image1",alt: "advertisement"%>
                <%= image_tag 'special_present',class:"slick1-image1",alt: "advertisement"%>
                <%= image_tag 'winter_sale',class:"slick1-image1",alt: "advertisement"%>
                <% 6.times do %>
                  <img class="slick1-image1" src="https://placehold.it/300x250" alt="advertisement">
                <% end %>
              </div>
              
              <%= link_to "マジックDEAL",magicdeal_path ,class:"slick-label" %>
              <div class="slick1">
                
                <% i=1 %>
                <% @items.each do |item| %>
                  <% if item.spoint == 40 && i<=8 %>
                    <%i +=1%>
                    <%= link_to item ,class:"slick1-image1" do %>
                      <p class="slick-spoint"><%=item.spoint%>%ポイントバック</p>
                      <%= image_tag (item.picture.url),class:"slick-image"%>
                      <p class="slick-name"><%=item.name%></p>
                      <p class="slick-price"><%=item.price%>円</p>
                    <% end %>
                  <% end %>
                <% end %>
              </div>
              
              <%= link_to "新着商品",items_path ,class:"slick-label" %>
              <div class="slick1">
                <% @items.first(10).each do |item| %>
                  <%= link_to item ,class:"slick1-image1" do %>
                    <%= image_tag (item.picture.url),class:"slick-image"%>
                    <p class="slick-name"><%=item.name%></p>
                    <p class="slick-price"><%=item.price%>円</p>
                  <% end %>
                <% end %>
              </div>
              
              
              <% i=1 %>
              <%= link_to '家電ランキング',{:controller=>"items",:action=>"index",:q=>{:category_eq=>'家電'}},class:"slick-label"%>
              <div class="slick1">
                <% @items_rank_kaden.first(10).each do |item| %>
                  <%= link_to item ,class:"slick1-image1" do %>
                    <span class="slick-rank"><%=i%>位</span>
                    <%i +=1%>
                    <%= image_tag (item.picture.url),class:"slick-image"%>
                    <p class="slick-name"><%=item.name%></p>
                    <p class="slick-price"><%=item.price%>円</p>
                  <% end %>
                <% end %>
              </div>
              
              
              <% i=1 %>
              <%= link_to '乗り物ランキング',{:controller=>"items",:action=>"index",:q=>{:category_eq=>'乗り物'}},class:"slick-label"%>
              <div class="slick1">
                <% @items_rank_norimono.first(10).each do |item| %>
                  <%= link_to item ,class:"slick1-image1" do %>
                    <span class="slick-rank"><%=i%>位</span>
                    <%i +=1%>
                    <%= image_tag (item.picture.url),class:"slick-image"%>
                    <p class="slick-name"><%=item.name%></p>
                    <p class="slick-price"><%=item.price%>円</p>
                  <% end %>
                <% end %>
              </div>
              
              <% i=1 %>
              <%= link_to '食品ランキング',{:controller=>"items",:action=>"index",:q=>{:category_eq=>'食品'}},class:"slick-label"%>
              <div class="slick1">
                <% @items_rank_food.first(10).each do |item| %>
                  <%= link_to item ,class:"slick1-image1" do %>
                    <span class="slick-rank"><%=i%>位</span>
                    <%i +=1%>
                    <%= image_tag (item.picture.url),class:"slick-image"%>
                    <p class="slick-name"><%=item.name%></p>
                    <p class="slick-price"><%=item.price%>円</p>
                  <% end %>
                <% end %>
              </div>
            </main>
          </div>
        </div>
    </div>
    <%= render 'layouts/footer' %>

app/views/static_pages/cafe.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <title>CSS Cafe</title>
    <meta name="description" content="CSS Cafeの公式Webサイトです。商品情報、店舗紹介、アクセス、会社情報など">
    <meta name="keywords" content="CSS Cafe, カフェ, コーヒー">
  </head>
  <body id="home">
    <!--header begin-->
    <header id="top">
    <h1>CSS Cafe</h1>
      <nav>
        <ul class="clearfix">
          <li class="current"><a href="index.html">ホーム</a></li>
          <li><a href="#">商品情報</a></li>
          <li><a href="#">店舗紹介</a></li>
          <li><a href="#">アクセス</a></li>
          <li><a href="#">会社情報</a></li>
          <li><a href="#">お問い合わせ</a></li>
        </ul>
       </nav>
    </header>
    <!--header end-->
    <!--main begin-->
    <main class="clearfix">
      <div id="main_image">
        <%= image_tag 'cafe.jpg', :size => '940x350', :alt => 'CSS cafe' %>
      </div>
      <!--main_content begin-->
      <div id="main_content">
        <section id="info">
          <h2>お知らせ</h2>
          <dl>
            <dt>2018年3月10日</dt>
            <dd>リニューアルオープンしました</dd>
            <dt>2018年4月15日</dt>
            <dd>4/27（金）は設備メンテナンスのため休業いたします。</dd>
            <dt>2018年4月20日</dt>
            <dd>ゴールデンウィークは休まず営業いたします</dd>
          </dl>
        </section>
        <section id="campain">
          <h2>キャンペーン情報</h2>
          <ul>
            <li>日頃の感謝を込めて、パスタ全品がいつもよりお得に！</li>
            <li>平日11時から14時までお得なランチタイムを実施中。</li>
            <li>バイオリン演奏付きのスペシャルディナーイベントの早期予約受付中。</li>
          </ul>
        <section>
      </div>
      <!--main_content end-->
      <!--sidebar begin-->
      <aside id="sidebar">
        <ul>
          <li>
            <a href="#">
            <img src="https://via.placeholder.com/300x200" alt="バナー1">
            </a>
          </li>
          <li>
            <a href="#">
            <img src="https://via.placeholder.com/300x200" alt="バナー2">
            </a>
          </li>
        </ul>
      </aside>
      <!--sidebar end-->
    </main>
    <!--main end-->
    <!--footer begin-->
    <footer>
      <ul>
        <li><a href="index.html">ホーム</a></li>
        <li><a href="#">商品情報</a></li>
        <li><a href="#">店舗紹介</a></li>
        <li><a href="#">会社情報</a></li>
        <li><a href="#">お問い合わせ</a></li>
      </ul>
      <small>&copy; 2018 CSS Cafe</small>
    </footer>
    <!--footer end-->
  </body>
</html>

app/views/static_pages/ec.html.erb
<% provide(:title, "EC") %>

  <head>
   <%= render 'arazin-head' %>
  </head>

app/views/static_pages/gallery.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <title>猫のフォトギャラリー</title>
    <meta name="description" content="かわいい猫のフォトギャラリー">
    <meta name="Keywords" content="猫,フォトギャラリー">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  </head>
  <body class="body_gallery">
    <!--ナビバー開始-->
    <!--fixed-topは上部で固定-->
    <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <!--<i class="far fa-images">はfontawesomeの選択したアイコン。mr-1はマージンライトの1-->
        <a class="navbar-brand" href="#"><i class="far fa-images mr-1"></i>Cats</a>
        <!--ハンバーガーメニュー-->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent"> 
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link active" href="#">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">New</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">About</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    
   <!--コンテナは12カラムのグリッドシステムにする-->
    <main class="container">
       <!--ジャンボトロン-->
      <div class="jumbotron">
        <h1><i class="fas fa-camera-retro"></i>フォトギャラリー</h1>
        <p>かわいい猫たちのフォトギャラリーをご覧ください。</p>
      </div>
    
    <!--写真をブレイクポイントで分けて表示する-->
      <div class="row">
        
        <!--グリッドはラージ以上で4カラム、スモール以上で6カラム-->
        <!--ラージ以上で写真を3列表示、ラージ未満スモール以上で写真を2列表示-->
        <!--mb-3はマージンボトムの5段階中の3-->
        <div class="col-lg-4 col-sm-6 mb-3">
          <div class="catgallery">
            <%= image_tag 'cat1.jfif',:alt => 'cat1'%>
          </div>
        </div>
        <div class="col-lg-4 col-sm-6 mb-3">
          <div class="catgallery">
            <%= image_tag 'cat2.jfif',:alt => 'cat2'%>
          </div>
        </div>
        <div class="col-lg-4 col-sm-6 mb-3">
          <div class="catgallery">
            <%= image_tag 'cat3.jfif',:alt => 'cat3'%>
          </div>
        </div>
        <div class="col-lg-4 col-sm-6 mb-3">
          <div class="catgallery">
            <%= image_tag 'cat4.jfif',:alt => 'cat4'%>
          </div>
        </div>
        <div class="col-lg-4 col-sm-6 mb-3">
          <div class="catgallery">
            <%= image_tag 'cat5.jfif',:alt => 'cat5'%>
          </div>
        </div>
        <div class="col-lg-4 col-sm-6 mb-3">
          <div class="catgallery">
            <%= image_tag 'cat6.jfif',:alt => 'cat6'%>
          </div>
        </div>
        <div class="col-lg-4 col-sm-6 mb-3">
          <div class="catgallery">
            <%= image_tag 'cat7.jfif',:alt => 'cat7'%>
          </div>
        </div>
        <div class="col-lg-4 col-sm-6 mb-3">
          <div class="catgallery">
            <%= image_tag 'cat8.jfif',:alt => 'cat8'%>
          </div>
        </div>
        <div class="col-lg-4 col-sm-6 mb-3">
          <div class="catgallery">
            <%= image_tag 'cat9.jfif',:alt => 'cat9'%>
          </div>
        </div>
      </div>
      
    </main>
    <!--fontawesomeを利用するための読み込み-->
    <script src="https://kit.fontawesome.com/31168af8af.js"></script>
  </body>
    
</html>

app/views/static_pages/histories.html.erb
<% provide(:title, 'Browsing_histories') %>
<%= render 'static_pages/arazin-top-menu'%>
<div class="row">
  <aside class="col-md-3">
    <section class="user_info">
      <%= render 'static_pages/arazin-side-menu'%>
    </section>
  </aside>
  
  <div class="col-md-9">
    <div class="user-put-up">
      <!--アイテムがあれば-->
      <% if @histories.any?%>
        <!--アイテム数-->
        <p class="put-up-count">閲覧した商品 (<%= @histories.count %>)</p>
        <ol class="items">
          <span class="item-pagination"><%= paginate @histories %></span>

          <% @histories.each do |histories| %>
            <div class="item_index ">
              <li id="histories-<%= histories.id %>">
                <div class="row">
                  <div class="col-md-2">
                    <%= image_tag histories.item.picture.url,class:"item_index_image"%>
                  </div>
                  <div class="col-md-7">
                    <div class="item_index_content">
                      <div class="item_name"><%= link_to histories.item.name, histories.item %></div>
                      <div class="item_content"><%=histories.item.content %></div>
                      <div class="item_user"><%= link_to histories.item.user.name, histories.item.user %></div>
                      
                    </div>
                  </div>
                  <div class="col-md-3">
                    <div class="item_price"><%=histories.item.price %>円</div>
                  </div>
            
              
                </div>
              </li>
            </div>
          
          <% end %>
          
        </ol>
      <% end %>
    </div>
  </div>
</div>

app/views/static_pages/home.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <title>CSS Cafe</title>
    <meta name="description" content="CSS Cafeの公式Webサイトです。商品情報、店舗紹介、アクセス、会社情報など">
    <meta name="keywords" content="CSS Cafe, カフェ, コーヒー">
  </head>
  <body id="home">
    <!--header begin-->
    <header id="top">
    <h1>CSS Cafe</h1>
      <nav>
        <ul class="clearfix">
          <li class="current"><a href="index.html">ホーム</a></li>
          <li><a href="#">商品情報</a></li>
          <li><a href="#">店舗紹介</a></li>
          <li><a href="#">アクセス</a></li>
          <li><a href="#">会社情報</a></li>
          <li><a href="#">お問い合わせ</a></li>
        </ul>
       </nav>
    </header>
    <!--header end-->
    <!--main begin-->
    <main class="clearfix">
      <div id="main_image">
        <%= image_tag 'cafe.jpg', :size => '940x350', :alt => 'CSS cafe' %>
      </div>
      <!--main_content begin-->
      <div id="main_content">
        <section id="info">
          <h2>お知らせ</h2>
          <dl>
            <dt>2018年3月10日</dt>
            <dd>リニューアルオープンしました</dd>
            <dt>2018年4月15日</dt>
            <dd>4/27（金）は設備メンテナンスのため休業いたします。</dd>
            <dt>2018年4月20日</dt>
            <dd>ゴールデンウィークは休まず営業いたします</dd>
          </dl>
        </section>
        <section id="campain">
          <h2>キャンペーン情報</h2>
          <ul>
            <li>日頃の感謝を込めて、パスタ全品がいつもよりお得に！</li>
            <li>平日11時から14時までお得なランチタイムを実施中。</li>
            <li>バイオリン演奏付きのスペシャルディナーイベントの早期予約受付中。</li>
          </ul>
        <section>
      </div>
      <!--main_content end-->
      <!--sidebar bigin-->
      <aside id="sidebar">
        <ul>
          <li>
            <a href="#">
            <img src="https://via.placeholder.com/300x200" alt="バナー1">
            </a>
          </li>
          <li>
            <a href="#">
            <img src="https://via.placeholder.com/300x200" alt="バナー2">
            </a>
          </li>
        </ul>
      </aside>
      <!--sidebar end-->
    </main>
    <!--main end-->
    <!--footer begin-->
    <footer>
      <ul>
        <li><a href="index.html">ホーム</a></li>
        <li><a href="#">商品情報</a></li>
        <li><a href="#">店舗紹介</a></li>
        <li><a href="#">会社情報</a></li>
        <li><a href="#">お問い合わせ</a></li>
      </ul>
      <small>&copy; 2018 CSS Cafe</small>
    </footer>
    <!--footer end-->
  </body>
</html>

app/views/static_pages/javascript.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <title>Hello World!</title>
  </head>
  <body>
  
  <!--javascriptでHello World!を出力-->
  <script>
    console.log('Hello World!');
  </script>
  
  <!--別ファイルのasset/javascripts/hello.jsを読み込む-->
  <%= javascript_include_tag "hello" %>
  
  <%= javascript_include_tag "calc" %>
  
  <!--別ファイルのイメージのasset/javascripts/holder.jsを読み込む-->
  <img data-src="holder.js/200x100" alt="image"/>
  
  </body>
</html>

app/views/static_pages/magicdeal.html.erb
<!--マジックディール-->
<% provide(:title, "Magicdeal") %>
<%= render 'static_pages/arazin-navbar' %>
<%= render 'static_pages/arazin-top-menu'%>
<div class="row">
  <aside class="col-md-3">
    <section class="side_info">
      <%= render 'static_pages/arazin-side-menu'%>
    </section>
  </aside>
  
  <div class="col-md-9">
    <h3 class="magic-title">マジックディール</h3>
    <div class = "magic-range">
    <p class="magic-point-comment">40%ポイントバックのアイテムをピックアップ！</p>
      <div class="row">
      
      <% i=1 %>
       <% @items.each do |item| %>
         <% if item.spoint == 40 && i<=8 %>
         <%i +=1%>
            <div class="col-md-3">
              <%= link_to item ,class:"slick1-image1" do %>
                <p class="slick-spoint"><%=item.spoint%>%ポイントバック</p>
                <%= image_tag (item.picture.url),class:"magic-image"%>
                <p class="slick-name"><%=item.name%></p>
                <p class="slick-price"><%=item.price%>円</p>
              <% end %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
    
      <div class = "magic-range">
        <p class="magic-point-comment">30%ポイントバックのアイテムをピックアップ！</p>
        <div class="row">
          <% i=1 %>
          <% @items.each do |item| %>
            <% if item.spoint == 30 && i<=8 %>
              <%i +=1%>
              <div class="col-md-3">
                <%= link_to item ,class:"slick1-image1" do %>
                  <p class="slick-spoint"><%=item.spoint%>%ポイントバック</p>
                  <%= image_tag (item.picture.url),class:"magic-image"%>
                  <p class="slick-name"><%=item.name%></p>
                  <p class="slick-price"><%=item.price%>円</p>
                <% end %>
              </div>
            <% end %>
          <% end %>
        </div> 
      </div>
    </div>
  </div>
</div>
<%= render 'layouts/footer' %>