config/routes.rb
Rails.application.routes.draw do

  # static
  root 'static_pages#arazin'
  
  get '/magicdeal',to:'static_pages#magicdeal'
  get '/ranking',to:'static_pages#ranking'
  get '/help',to:'static_pages#help'
  get '/ec',to:'static_pages#ec'  # 出店(暫定)
  
  get '/histories',to:'static_pages#histories'
  get '/clips',to:'static_pages#clips'
  get '/boughts',to:'static_pages#boughts'
  
  
  # users
  get '/signup',to: 'users#new'
  post '/signup',  to: 'users#create'
  
  # sessions
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :relationships,       only: [:create, :destroy]
  
  resources :items do
    member do
      post "add_clip", to: "clips#create"
    end
  end
  
  resources :clips, only: [:destroy]
  
  # カート
  resources :carts, only: [:show]
  
  post '/add_item', to:'carts#add_item'
  post '/update_item', to: 'carts#update_item'
  delete '/delete_item', to: 'carts#delete_item'
  
  post '/cart_login', to:'carts#cart_login'
  get '/cart_login', to:'carts#cart_login'
  
  # get '/cart_login',to:'carts#cart_login'
  post '/cart_login_create', to:'carts#cart_login_create'
  
  get '/pay_view',to:'carts#pay_view'
  post '/pay_view', to:'carts#pay'
  
  # resources :cards
  get '/card_create',to: 'cards#new'
  post '/card_create',to: 'cards#create'

  get '/pay_confirmation',to:'carts#pay_confirmation'

  # 他のポートフォリオ
  get '/cafe',to:'static_pages#cafe'
  get '/gallery',to: 'static_pages#gallery'
  get '/lp1',to: 'static_pages#lp1'
  get '/black_jack',to: 'static_pages#black_jack'
end

app/models/user.rb
class User < ApplicationRecord
  # items,cartsと紐付ける、ユーザーと一緒に破棄される
  has_many :items, dependent: :destroy, through: :clips
  has_many :histories, dependent: :destroy
  has_many :clips, dependent: :destroy
  has_many :boughts, dependent: :destroy
  has_many :cards
  
  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy
                                  
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
                                   
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  
  # 仮想のremember_token属性を作成する(データベースにはないがuser.remember_tokenが使える)
  attr_accessor :remember_token
  
  # save前にメールアドレスを小文字にして保存する
  before_save { email.downcase! }
  # 名前が空白、51文字以上(twitterに準拠)でfalse
  
  has_many :items, dependent: :destroy
  validates :name,  presence: true, length: { maximum: 50 }
  
  # メールアドレスが空白、257文字以上(RFC 5321に準拠)でfalse
  # 有効な正規表現に当てはまらなければfalse
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 256 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false } #大文字小文字を問わず一意でなければfalse
  
  # セキュアなパスワードにするためのメソッド
  has_secure_password
  # パスワードが空白、8文字以下でfalse 変更時はnilでも可。新規登録時はhas_secure_passwordによりnilはエラーになる
  validates :password, presence: true, allow_nil: true
  
  #パスワードの長さは8〜128文字,大文字と小文字と数字と特殊文字をそれぞれ1文字以上
  validate :password_complexity
  def password_complexity
    return if password.blank? || password =~ /^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-]).{8,128}$/
    errors.add :password, "パスワードの強度が不足しています。パスワードの長さは8文字以上、大文字と小文字と数字と特殊文字をそれぞれ1文字以上含める必要があります。"
  end
  
  # kaminariのページネーション設定
  default_scope -> { order(created_at: :desc) }
  # 1ページに表示させる数
  # paginates_per 30
  
   # 渡された文字列のハッシュ値を返す
  def User.digest(string)
    # テスト中のコストは最小(本番はあげる必要がある)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    # ハッシュ化
    BCrypt::Password.create(string, cost: cost)
  end
  
  # ランダムなトークンを返す(記憶トークンに使う)
  def User.new_token
    # 64種類の文字からランダムに22個選ばれる
    SecureRandom.urlsafe_base64
  end
  
  # 記憶トークンを作成し、ハッシュ化したものを記憶ダイジェストにする。
  # その後記憶ダイジェストをデータベースへ保存する
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  # 渡されたトークンがダイジェストと一致したらtrueを返す(has_secure_passwordのと名前は同じだが別物)
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  # データベースの記憶ダイジェストを消す
  def forget
    update_attribute(:remember_digest, nil)
  end
  
  # ユーザーをフォローする
  def follow(other_user)
    # 最後の配列に追記
    following << other_user
  end

  # ユーザーをフォロー解除する
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # 現在のユーザーがフォローしてたらtrueを返す
  def following?(other_user)
    following.include?(other_user)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # 事前にログイン済みユーザーかどうか確認
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy, :following, :followers]
  
  # 事前に正しいユーザーかどうか確認
  before_action :correct_user,   only: [:edit, :update]
  
  # 事前に管理者かどうか確認
  before_action :admin_user,     only: :destroy
  
  # ユーザー一覧を表示する /users
  def index
    # すべてのユーザーをよびだす
    # paginateのkaminariに渡せる形で渡す
    @users = User.page(params[:page])
  end

  # 会員ページ　/users/:id  user_path(user)
  def show
    @user = User.find(params[:id])
    @items = @user.items.page (params[:page])
    
    # redirect_to root_url and return unless @user.activated 
    
  end
  
  # 新規会員登録　/signup　
  def new
    @user = User.new
  end
  
  # signupページのformに入力された内容をpostしたとき
  def create
    # Strong Parametersを使ってデータを受け取る
    @user = User.new(user_params)
    if @user.save
      # log_inメソッドで一時cookiesにuser.idを暗号化して保存する
      log_in @user
      
      # フラッシュメッセージ
      flash[:success] = "新規会員登録が成功しました"
      
      # ルートへリダイレクト(後で、成功画面を作成して、リダイレクト先を変える)
      redirect_to root_path
    else
      render 'new'
    end
  end 
  
  # 会員編集ページへのアクセス
  def edit
  end
  
  # 会員ページの編集フォームを送信
  def update
    if @user.update_attributes(user_params)
      flash[:success] = "編集内容を保存しました"
      
      # ユーザーshowページへリダイレクト
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  # 管理者権限がある場合、indexページからユーザーを削除する
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end
  
  def following
    @title = "Following"
    @user  = User.find(params[:id])
    @users = @user.following.page(params[:page])
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user  = User.find(params[:id])
    @users = @user.followers.page(params[:page])
    render 'show_follow'
  end
  
  # 外部から操作できない
  private

    # ユーザー新規作成・編集時に許可するパラメータ
    def user_params
      # :user属性を必須とし、その上で各属性を許可する
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
    
    # beforeアクション
    
    # 管理者かどうか確認
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper

  # 引数で与えられたユーザーのGravatar画像を返す
  # キーワード引数でデフォルトのsizeを80にする
  def gravatar_for(user, size: 80)
    # Digestライブラリのhexdigestメソッドを使って、MD5のハッシュ化をする
    # ハッシュ化前にメールアドレスを小文字にする
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete }, remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/edit.html.erb
<!--会員情報の編集-->
<% provide(:title, "Edit user") %>

<div class="col-md-6 ml-auto mr-auto">
  <div class="user-edit-form">
    <p class="kaiinn-sigh-up">会員情報の編集</p>
    <!--@userの属性情報から引き出す-->
    <!--データベースに既存のユーザーがあれば、リクエストはPATCHになる-->
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <p class="sigh-up-label">ユーザーネーム</p>
      <%= f.text_field :name, class: 'form-control' %>

      <p class="sigh-up-label">メールアドレス</p>
      <%= f.email_field :email, class: 'form-control' %>

      <p class="sigh-up-label">パスワード</p>
      <p class="sigh-up-password"><8文字以上、大文字と小文字,数字と特殊文字をそれぞれ1文字以上></p>
      <%= f.password_field :password, class: 'form-control' %>

      <p class="sigh-up-label">パスワード確認用</p>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "変更", class: "btn btn-primary" %>
    <% end %>

    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <!--rel = "noopener"を付けるとtarget="_blank"したときのフィッシングを防げる-->
      <a href="http://gravatar.com/emails" target="_blank" rel = "noopener">画像の変更</a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>ユーザー一覧</h1>

<div class="paginate"><%= paginate @users %></div>

<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= gravatar_for user, size: 50 %>
      <%= link_to user.name, user %>
      
      <!--管理者権限がある場合かつ、現在のユーザーではない（管理者自身は削除リンクをださない）-->
      <% if current_user.admin? && !current_user?(user) %>
        <%= link_to "delete", user, method: :delete,
                                      data: { confirm: "確認：削除してもよろしいですか？" } %>
      <% end %>
    </li>
  <% end %>
  <div class="pagination"><%= paginate @users %></div>
</ul>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>

<div class="col-md-6 ml-auto mr-auto">
  <div class="sigh-up-form">
    <p class="kaiinn-sigh-up">会員登録</p>
    <!--/signup に対して送信する-->
    <%= form_for(@user, url: signup_path) do |f| %>
      <!--エラーメッセージ-->
      <%= render 'shared/error_messages', object: f.object %>
      
      <p class="sigh-up-label">ユーザーネーム</p>
      <%= f.text_field :name, class: 'form-control' %>

      <p class="sigh-up-label">メールアドレス</p>
      <%= f.email_field :email, class: 'form-control' %>

      <p class="sigh-up-label">パスワード</p>
      <p class="sigh-up-password"><8文字以上、大文字と小文字,数字と特殊文字をそれぞれ1文字以上></p>
      <%= f.password_field :password, class: 'form-control' %>

      <p class="sigh-up-label">パスワード確認用</p>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "登録", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<!--プロフィール（会員情報）-->
<% provide(:title, @user.name) %>
<%= render 'static_pages/arazin-top-menu'%>
<div class="row">
  <aside class="col-md-4">
    <div class="user_info">
      
        <%= gravatar_for @user %>
        <p><%= @user.name %></p>
        <section class="stats">
          <%= render 'shared/stats' %>
        </section>
        <% if current_user?(@user) %>
          <div>
            <p><%= link_to "ユーザー設定の変更", edit_user_path(current_user) %></p>
          </div>
          <div>
            <p> <%= link_to "商品出品登録",new_item_path %></p>
          </div>
          
        <% end %>

      
    </div>
  </aside>
  <div class="col-md-8">
    <div class="user-put-up">
      <%= render 'follow_form' if logged_in? %>
      <!--アイテムがあれば-->
      <% if @user.items.any?%>
        <!--アイテム数-->
        <p class="put-up-count">出品している商品 (<%= @user.items.count %>)</p>
        <ol class="items">
          <%= render "items/items" %>
        </ol>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<%= render 'static_pages/arazin-top-menu'%>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= gravatar_for @user %>
      <p><%= @user.name %></p>
      <p class="return-kaiin"><%= link_to "会員ページに戻る", @user %></p>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
      <% if @users.any? %>
        <div class="user_avatars">
          <% @users.each do |user| %>
            <%= link_to gravatar_for(user, size: 30), user %>
          <% end %>
        </div>
      <% end %>
    </section>
  </aside>
  <div class="col-md-8">
    <h3 class="follow-title"><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users follow">
        <% @users.each do |user| %>
        <li>
          <%= gravatar_for user, size: 50 %>
          <%= link_to user.name, user %>
        </li>
        <% end %>
       
      </ul>
      <div class="paginate"><%= paginate @users %></div>
    <% end %>
  </div>
</div>