config/routes.rb
Rails.application.routes.draw do

  # static
  root 'static_pages#arazin'
  
  get '/magicdeal',to:'static_pages#magicdeal'
  get '/ranking',to:'static_pages#ranking'
  get '/help',to:'static_pages#help'
  get '/ec',to:'static_pages#ec'  # 出店(暫定)
  
  get '/histories',to:'static_pages#histories'
  get '/clips',to:'static_pages#clips'
  get '/boughts',to:'static_pages#boughts'
  
  
  # users
  get '/signup',to: 'users#new'
  post '/signup',  to: 'users#create'
  
  # sessions
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :relationships,       only: [:create, :destroy]
  
  resources :items do
    member do
      post "add_clip", to: "clips#create"
    end
  end
  
  resources :clips, only: [:destroy]
  
  # カート
  resources :carts, only: [:show]
  
  post '/add_item', to:'carts#add_item'
  post '/update_item', to: 'carts#update_item'
  delete '/delete_item', to: 'carts#delete_item'
  
  post '/cart_login', to:'carts#cart_login'
  get '/cart_login', to:'carts#cart_login'
  
  # get '/cart_login',to:'carts#cart_login'
  post '/cart_login_create', to:'carts#cart_login_create'
  
  get '/pay_view',to:'carts#pay_view'
  post '/pay_view', to:'carts#pay'
  
  # resources :cards
  get '/card_create',to: 'cards#new'
  post '/card_create',to: 'cards#create'

  get '/pay_confirmation',to:'carts#pay_confirmation'

  # 他のポートフォリオ
  get '/cafe',to:'static_pages#cafe'
  get '/gallery',to: 'static_pages#gallery'
  get '/lp1',to: 'static_pages#lp1'
  get '/black_jack',to: 'static_pages#black_jack'
end

app/models/cart.rb
class Cart < ApplicationRecord
   has_many :citems
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :setup_cart_item!, only: [:add_item, :update_item, :delete_item]

  def show
    @citems = current_cart.citems
  end

  # item/showから、「カートに入れる」を押した時のアクション
  def add_item
    if @citem.blank?
      @citem = current_cart.citems.build(item_id: params[:item_id])
    end
    
    @citem.quantity += params[:quantity].to_i
    @citem.save
    redirect_to current_cart
  end
  
  # カート詳細画面から、「更新」を押した時のアクション
  def update_item
    @citem.update(quantity: params[:quantity].to_i)
    redirect_to current_cart
  end

 # カート詳細画面から、「削除」を押した時のアクション
  def delete_item
    @citem.destroy
    redirect_to current_cart
  end
  
  # カート詳細画面から、「購入する」を押した時のアクション
  def cart_login
    session[:item_id] = params[:item_id]
  end

  # カートのログイン画面から「ログイン」を押した時のアクション
  def cart_login_create
    @user = User.find_by(email: params[:session][:email].downcase)
    # 有効なユーザーでかつ正しいパスワードか
    if @user && @user.authenticate(params[:session][:password])
      # ログインする
      log_in @user
      
      # チェックボックスにチェックが入っていればremember(@user)、入っていなければforget(@user)
      # remember(user)は記憶トークンから記憶ダイジェストにしデータベースへ保存
      # さらに永続的クッキーにユーザーidと記憶トークンを保存
      params[:session][:remember_me] == '1' ? remember(@user) : forget(@user)
      
      # 記憶したURL (もしくはルートパス) にリダイレクト
      redirect_to pay_view_path
      
    else
      # flash.nowとすると、別のリクエストが来たときに消える
      flash.now[:danger] = 'メールアドレスとパスワードの組み合わせが無効です。'
      # ログインフォームを再表示
      render 'cart_login'
    end
  end
  
  def pay_view
    @citem = current_cart.citems.find_by(item_id: session[:item_id])
    if @citem.nil?
      flash[:danger] = 'エラーが発生しました。再度やり直しをお願いします'
      redirect_to current_cart
    end
  end
  
  def pay_confirmation
    @bought = Bought.find_by(item_id: session[:item_id])
  end
  
  private

  # 現在のカートからアイテムを特定する
  def setup_cart_item!
    @citem = current_cart.citems.find_by(item_id: params[:item_id])
  end
  
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/cart_login.html.erb
<!--ログイン画面-->
<% provide(:title, "Cart_Log in") %>

<div class="row cart-top">
  <div class="col-lg-1 col-sm-2">
    <div class="arazin-title">
      <h1><%= link_to "Zin", root_path %></h1>
    </div>
  </div>
  
  <!--カラムのセンター寄せ-->
  <div class="col-lg-6 col-sm-9 ml-auto mr-auto ">
    <div class="cart-process">
      <p class="cart-cart">買い物かご</p>
      <p class="cart-bar">ー</p>
      <p class="cart-login-current">ログイン</p>
      <p class="cart-bar">ー</p>
      <p class="cart-pay">お支払い方法</p>
      <p class="cart-bar">ー</p>
      <p class="cart-confirm">お支払い完了</p>
    </div>
  </div>
</div>
  

<div class="col-md-6 ml-auto mr-auto">
  <div class="login-form">
    <p class="kaiinn-login">会員ログイン</p>
    <%= form_for(:session, url: cart_login_create_path) do |f| %>

      <p class="login-label">メールアドレス</p>
      <%= f.email_field :email, class: 'form-control' %>
      <p class="login-general">一般ユーザー：general@arazin.org</p>
      <p>管理者　　　：admin@arazin.org</p>

      <p class="login-label">パスワード</p>
      <%= f.password_field :password, class: 'form-control' %>
      <p class="login-general">一般ユーザー：2arazinzinG$</p>
      <p>管理者　　　：1arazinzinA$</p>
      
      <%= f.label :remember_me, class: "checkbox inline" do %>
        <%= f.check_box :remember_me %>
        <span>ログアウトしない限り、ログインを保持する</span>
      <% end %>

      <%= f.submit "ログイン", class: "btn btn-primary" %>
    <% end %>

    <p>まだ会員登録されていない方　 <%= link_to "新規登録（無料）", signup_path %></p>
  </div>
</div>

app/views/carts/pay_confirmation.html.erb
<% provide(:title, "Cart_confirmation") %>

<div class="row cart-top">
  <div class="col-lg-1 col-sm-2">
    <div class="arazin-title">
      <h1><%= link_to "Zin", root_path %></h1>
    </div>
  </div>
  
  <!--カラムのセンター寄せ-->
  <div class="col-lg-6 col-sm-9 ml-auto mr-auto ">
    <div class="cart-process">
      <p class="cart-cart">買い物かご</p>
      <p class="cart-bar">ー</p>
      <p class="cart-login">ログイン</p>
      <p class="cart-bar">ー</p>
      <p class="cart-pay">お支払い方法</p>
      <p class="cart-bar">ー</p>
      <p class="cart-confirm-current">お支払い完了</p>
    </div>
  </div>
</div>

<div class="row justify-content-center">
  <div class="col-md-6 col-md-offset-3">
    <p>お支払いが完了しました</p>
    <div class="login-form">

      <p class="pay-view">ご購入された商品</p>
      <div class="row">
        
        <div class="col-md-6">
          <%= image_tag @bought.item.picture.url,class:"pay-image"%>
        </div>
        
        <div class="col-md-5 ">
          <p>商品名：<%=@bought.item.name%></p>
          <p>金額 (単品):<%=@bought.item.price%>円</p>
          <p>個数：<%=@bought.quantity%></p>
          <p>金額 (合計)：<%=(@bought.item.price)*(@bought.quantity)%>円</p>
          <p>獲得ポイント：<%=((@bought.item.price)*(@bought.quantity)/100)+((@bought.item.spoint)*0.01*(@bought.item.price)*(@bought.quantity)).round%>pt</p>
        </div>
      </div>
    </div>
    <p class="pay-return"><%= link_to "トップページに戻る", root_path %><p>
  </div>
</div>

app/views/carts/pay_view.html.erb
<% provide(:title, "Cart_pay") %>

<div class="row cart-top">
  <div class="col-lg-1 col-sm-2">
    <div class="arazin-title">
      <h1><%= link_to "Zin", root_path %></h1>
    </div>
  </div>
  
  <!--カラムのセンター寄せ-->
  <div class="col-lg-6 col-sm-9 ml-auto mr-auto ">
    <div class="cart-process">
      <p class="cart-cart">買い物かご</p>
      <p class="cart-bar">ー</p>
      <p class="cart-login">ログイン</p>
      <p class="cart-bar">ー</p>
      <p class="cart-pay-current">お支払い方法</p>
      <p class="cart-bar">ー</p>
      <p class="cart-confirm">お支払い完了</p>
    </div>
  </div>
</div>

<div class="row justify-content-center">
  <div class="col-md-6 col-md-offset-3">
    <div class="login-form">

      <p class="pay-view">購入画面</p>
      <div class="row">
        
        <div class="col-md-6">
          <%= image_tag @citem.item.picture.url,class:"pay-image"%>
        </div>
        
        <div class="col-md-5 ">
          <p>商品名：<%=@citem.item.name%></p>
          <p>金額 (単品):<%=@citem.item.price%>円</p>
          <p>個数：<%=@citem.quantity%></p>
          <p>金額 (合計)：<%=(@citem.item.price)*(@citem.quantity)%>円</p>
          <p>獲得ポイント：<%=((@citem.item.price)*(@citem.quantity)/100)+((@citem.item.spoint)*0.01*(@citem.item.price)*(@citem.quantity)).round%>pt</p>
          <%= form_with(url:card_create_path, method: :get, class: "cart-payment",local: true) do |f| %>
            <%= f.hidden_field :amount, { value: (@citem.item.price)*(@citem.quantity)} %>
            <%= f.hidden_field :quantity, { value: @citem.quantity} %>
            <%= f.hidden_field :points, { value: ((@citem.item.price)*(@citem.quantity)/100)+((@citem.item.spoint)*0.01*(@citem.item.price)*(@citem.quantity)).round} %>
            <%= f.submit "クレジットカード画面", class: "btn-pay" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/carts/show.html.erb
<% provide(:title, "Cart") %>

<div class="row cart-top">
  <div class="col-lg-1 col-sm-2">
    <div class="arazin-title">
      <h1><%= link_to "Zin", root_path %></h1>
    </div>
  </div>
  
  <!--カラムのセンター寄せ-->
  <div class="col-lg-6 col-sm-9 ml-auto mr-auto ">
    <div class="cart-process">
      <p class="cart-cart-current">買い物かご</p>
      <p class="cart-bar">ー</p>
      <p class="cart-login">ログイン</p>
      <p class="cart-bar">ー</p>
      <p class="cart-pay">お支払い方法</p>
      <p class="cart-bar">ー</p>
      <p class="cart-confirm">お支払い完了</p>
    </div>
  </div>
</div>

<div class="cart-comment">
  <h5>買い物かごの商品</h2>
</div>

<ol>
  <% @citems.each do |citem| %>
    <div class="row cart-content">
      <div class="col-lg-2 col-sm-4">
        <div class="cart-left">
          <p><%= link_to citem.item.user.name, citem.item.user %></p>
          <% unless citem.item.spoint == 0 %>
            <p class="cart-magic-heading">マジックディール対象商品</p>
            <p class="cart-magic-pointback1"><%=citem.item.spoint%>%ポイントバック<p>
            <p class="cart-magic-pointback2">お1つにつき</p>
            <p class="cart-magic-pointget"><%=((citem.item.spoint)*0.01*(citem.item.price)).round%>ポイント獲得！</p>
        <% end %>
        </div>
      </div>
      
      <div class="col-lg-6 col-sm-8">
        <div class="cart-middle">
            
          <div class="row">
            <div class="col-md-6">
              <%= image_tag citem.item.picture.url,class:"cart_image"%>
            </div>
            
            <div class="col-md-6">
              <p><%= link_to citem.item.name, citem.item %></p>
              <div class="cart-middle-charge clearfix">
                <p class="cart-middle-price"><%=citem.item.price%>円</p>
                <p class="cart-middle-souryou ">送料別</p>
              </div>
              <div class="cart-middle-quantity">
                <%= form_with(url:update_item_path, method: :post, class: "form-quantity",local: true) do |f| %>
                
                  <%= f.hidden_field :item_id, { value: citem.item_id} %>
    
            
                  <p class ="item-quantity-label">数量</p>
                  
                  <!--selectのクラス指定は{}をはさむ必要がある-->
                  <%= f.select :quantity ,[1,2,3,4,5,6,7,8,9,10],{},class: "cart-quantity"%>
                  <%= f.submit "個数を変更", class: "btn-quantity" %>
                
                <% end %>
              </div>
              
              <p class>通常6～10日以内に発送予定</p>
              
              <%= form_with(url:delete_item_path, method: :delete, class: "form-delete",local: true) do |f| %>
                
                  <%= f.hidden_field :item_id, { value: citem.item_id} %>
                  <%= f.submit "カートから削除", class: "btn-delete" %>
                
              <% end %>
            </div>
            
          </div>
          
        </div>
      </div>
      
      <div class="col-lg-3 col-sm-8 ml-auto mr-auto">
        <div class="cart-right">

          <%= form_with(url:cart_login_path, method: :post, class: "cart-payment",local: true) do |f| %>
            <%= f.hidden_field :item_id, { value: citem.item_id} %>
            <%= f.submit "ご購入手続き", class: "btn-pay" %>
          <% end %>
          
          <p class="cart-sum">小計 (数量：<%=citem.quantity%>)</p>
          <p class="cart-right-price"><%=(citem.item.price)*(citem.quantity)%>円</p>
        
          <div class="cart-point">
            <p class="cart-point-plan">獲得予定ポイント</p>
            <p class="cart-pointget"><%=((citem.item.price)*(citem.quantity)/100)+((citem.item.spoint)*0.01*(citem.item.price)*(citem.quantity)).round%>ポイント</p>
            <p class="cart-point-en">(円相当)</p>
            <p class="cart-point-comment1">次ページで会員登録（無料）をした場合、このポイントを獲得できます</p>
            <p class="cart-point-comment2"><i class="fas fa-exclamation-circle"></i>一部の倍率・ポイントが反映されていない場合があります</p>
            <p class="cart-point-comment3"><i class="fas fa-exclamation-circle"></i>獲得上限にご注意ください。実際の獲得ポイントと異なる場合があります</p>
          </div>
        </div>
      </div>
    </div>
  <%end%>
</ol>